### PR TITLE
added nginx proxy for the cardshop warehouse

### PR DESCRIPTION
**Pull request by rgaudin**
Simple copy-paste of other rules in docker compose and sites folder.

Is that all it takes?

### CODE REVIEW

**Comment by kelson42** [comment]
@rgaudin Would not that be a better approach to have a separate docker-compose file like https://github.com/kiwix/maintenance/blob/master/matomo-server-docker/docker-compose.yml. To me this does not belong to the core download.kiwix.org service.

**Comment by rgaudin** [comment]
Sure ; I'll prepare one.

**Comment by kelson42** [comment]
@rgaudin What should we do with this PR?

**Comment by rgaudin** [comment]
Not relevant anymore.

**Pull request closed without merging**
